//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmaShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.DepartmentProduct = new HashSet<DepartmentProduct>();
            this.StaffPosts = new HashSet<StaffPosts>();
        }
    
        public int ID_department { get; set; }

        private string _departName;
        public string department_name
        {
            get
            {
                return _departName;
            }
            set
            {
                if (value != string.Empty)
                {
                    _departName = value;
                }
            }
        }

        private string _departAddress;
        public string address_name
        {
            get
            {
                return _departAddress;
            }
            set
            {
                if (value != string.Empty)
                {
                    _departAddress = value;
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentProduct> DepartmentProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffPosts> StaffPosts { get; set; }
    }
}
