//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmaShop
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Customs = new HashSet<Customs>();
            this.DepartmentProduct = new HashSet<DepartmentProduct>();
        }
    
        public int ID_product { get; set; }
        public int productType_ID { get; set; }

        private string _product;
        public string product_name
        {
            get
            {
                return _product;
            }
            set
            {
                if (value != string.Empty)
                {
                    _product = value;
                }
            }
        }

        private decimal _price;
        public decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                if (value > 0)
                {
                    _price = value;
                }
                else
                {
                    MessageBox.Show("Цена не может быть отрицательной!", "Ошибка!", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }

        private int _amount;
        public int amount
        {
            get
            {
                return _amount;
            }
            set
            {
                if (value > 0)
                {
                    _amount = value;
                }
                else
                {
                    MessageBox.Show("Количество не может быть отрицательным!", "Ошибка!", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customs> Customs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentProduct> DepartmentProduct { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
