//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmaShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_staff { get; set; }

        private string _lastName;
        public string last_name
        {
            get
            {
                return _lastName;
            }
            set
            {
                if (value != string.Empty)
                {
                    _lastName = value;
                }
            }
        }

        private string _firstName;
        public string first_name
        {
            get
            {
                return _firstName;
            }
            set
            {
                if (value != string.Empty)
                {
                    _firstName = value;
                }
            }
        }

        private string _midName;
        public string middle_name
        {
            get
            {
                return _midName;
            }
            set
            {
                if (value != string.Empty)
                {
                    _midName = value;
                }
            }
        }
        public Nullable<int> account_ID { get; set; }
        public int post_ID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual StaffPosts StaffPosts { get; set; }
    }
}
